// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductService.ApplicationDbContext;

#nullable disable

namespace ProductService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231006062937_initial-create")]
    partial class initialcreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductService.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 10, 6, 6, 29, 37, 104, DateTimeKind.Utc).AddTicks(7762),
                            Description = "Description 1",
                            Name = "Product 1",
                            Price = 10m,
                            Status = true,
                            Stock = 10
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 10, 6, 6, 29, 37, 104, DateTimeKind.Utc).AddTicks(7792),
                            Description = "Description 2",
                            Name = "Product 2",
                            Price = 20m,
                            Status = true,
                            Stock = 20
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 10, 6, 6, 29, 37, 104, DateTimeKind.Utc).AddTicks(7794),
                            Description = "Description 3",
                            Name = "Product 3",
                            Price = 30m,
                            Status = true,
                            Stock = 30
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 10, 6, 6, 29, 37, 104, DateTimeKind.Utc).AddTicks(7795),
                            Description = "Description 4",
                            Name = "Product 4",
                            Price = 40m,
                            Status = true,
                            Stock = 40
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 10, 6, 6, 29, 37, 104, DateTimeKind.Utc).AddTicks(7796),
                            Description = "Description 5",
                            Name = "Product 5",
                            Price = 50m,
                            Status = true,
                            Stock = 50
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2023, 10, 6, 6, 29, 37, 104, DateTimeKind.Utc).AddTicks(7800),
                            Description = "Description 6",
                            Name = "Product 6",
                            Price = 60m,
                            Status = true,
                            Stock = 60
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2023, 10, 6, 6, 29, 37, 104, DateTimeKind.Utc).AddTicks(7801),
                            Description = "Description 7",
                            Name = "Product 7",
                            Price = 70m,
                            Status = true,
                            Stock = 70
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2023, 10, 6, 6, 29, 37, 104, DateTimeKind.Utc).AddTicks(7802),
                            Description = "Description 8",
                            Name = "Product 8",
                            Price = 80m,
                            Status = true,
                            Stock = 80
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2023, 10, 6, 6, 29, 37, 104, DateTimeKind.Utc).AddTicks(7803),
                            Description = "Description 9",
                            Name = "Product 9",
                            Price = 90m,
                            Status = true,
                            Stock = 90
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2023, 10, 6, 6, 29, 37, 104, DateTimeKind.Utc).AddTicks(7805),
                            Description = "Description 10",
                            Name = "Product 10",
                            Price = 100m,
                            Status = true,
                            Stock = 100
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
